---
title: "Modeling"
author: "Ryan Friedman"
format: html
editor: visual
---

## 1.  Introduction

This document continues from the water potability dataset EDA with the goal of selecting a model the predicts potability from the other variables.  Both classification tree and random forest models will be considered, and the winning model selected.

[Click here to return to the EDA Page](EDA.html)

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(knitr)
library(gt)
library(tidymodels)
```

## 2. Preparation for Modeling

- Split the data

- Define the recipe

## 3. Classification Tree Model

- Describe and specify the model

- Create the workflow

- Fit the model for varying values of complexity

- Select the best tuned classification tree model and do a last fit

## 4. Random Forest Model

- Describe and specify the model

- Create the workflow

- Fit the model for varying values of mtry

- Select the best tuned random forest model and do a last fit

## 5. Model Comparison

- Model variable importance comparison

- Model performance comparison

- Declare an overall winner